/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MessageBoardInterface extends Interface {
  getFunction(nameOrSignature: "postMessage"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MessagePosted"): EventFragment;

  encodeFunctionData(functionFragment: "postMessage", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "postMessage",
    data: BytesLike
  ): Result;
}

export namespace MessagePostedEvent {
  export type InputTuple = [sender: AddressLike, message: string];
  export type OutputTuple = [sender: string, message: string];
  export interface OutputObject {
    sender: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MessageBoard extends BaseContract {
  connect(runner?: ContractRunner | null): MessageBoard;
  waitForDeployment(): Promise<this>;

  interface: MessageBoardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  postMessage: TypedContractMethod<[message: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "postMessage"
  ): TypedContractMethod<[message: string], [void], "nonpayable">;

  getEvent(
    key: "MessagePosted"
  ): TypedContractEvent<
    MessagePostedEvent.InputTuple,
    MessagePostedEvent.OutputTuple,
    MessagePostedEvent.OutputObject
  >;

  filters: {
    "MessagePosted(address,string)": TypedContractEvent<
      MessagePostedEvent.InputTuple,
      MessagePostedEvent.OutputTuple,
      MessagePostedEvent.OutputObject
    >;
    MessagePosted: TypedContractEvent<
      MessagePostedEvent.InputTuple,
      MessagePostedEvent.OutputTuple,
      MessagePostedEvent.OutputObject
    >;
  };
}
