/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { MessageBoard, MessageBoardInterface } from "../MessageBoard";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "MessagePosted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "postMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061024e806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80636630f88f14610030575b600080fd5b61004a600480360381019061004591906100fa565b61004c565b005b7ffe7cdc2459269b5bc10478528a21029a11424d593a2c88471f4f5cfb582765b733838360405161007f939291906101e6565b60405180910390a15050565b600080fd5b600080fd5b600080fd5b600080fd5b600080fd5b60008083601f8401126100ba576100b9610095565b5b8235905067ffffffffffffffff8111156100d7576100d661009a565b5b6020830191508360018202830111156100f3576100f261009f565b5b9250929050565b600080602083850312156101115761011061008b565b5b600083013567ffffffffffffffff81111561012f5761012e610090565b5b61013b858286016100a4565b92509250509250929050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061017282610147565b9050919050565b61018281610167565b82525050565b600082825260208201905092915050565b82818337600083830152505050565b6000601f19601f8301169050919050565b60006101c58385610188565b93506101d2838584610199565b6101db836101a8565b840190509392505050565b60006040820190506101fb6000830186610179565b818103602083015261020e8184866101b9565b905094935050505056fea26469706673582212204dac77cdd109a063a765f71e36b4c4b178369be446d90ce8d2a7c528b9e4812a64736f6c63430008150033";

type MessageBoardConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MessageBoardConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MessageBoard__factory extends ContractFactory {
  constructor(...args: MessageBoardConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MessageBoard & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MessageBoard__factory {
    return super.connect(runner) as MessageBoard__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MessageBoardInterface {
    return new Interface(_abi) as MessageBoardInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MessageBoard {
    return new Contract(address, _abi, runner) as unknown as MessageBoard;
  }
}
